name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the code
      - name: Lint code with flake8
        run: |
          source .venv/bin/activate
          pip install flake8
          flake8 .

      # Run tests
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=5 --disable-warnings
